name: Test all python solutions
on: push
jobs:
  test-all-solutions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
      - name: setup rye environment
        run: |
          cd python
          rye sync --no-dev --no-lock
      - name: run tests
        run: |
          cd python
          echo '```plaintext' >> $GITHUB_STEP_SUMMARY
          rye run python test_all.py | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
